databases:
  - name: statsprofiledb
    plan: free
    databaseName: statsprofile
    user: statsuser

services:
  - type: web
    plan: free
    name: statsprofile
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn statsprofile.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: statsprofiledb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4